const clientes = [
  {
    id: 1,
    name: 'Ley',
    apellidos: 'Avila',
    ci: '8448556',
    direccion: 'c/las palmas',
    genero: 'femenino',
    numero: '77049140',
    image: require('../assets/images/clientes/animewo.png'),
  },
  {
    id: 2,
    name: 'Jose',
    apellidos: 'Avila',
    ci: '8448556',
    direccion: 'c/las palmas',
    genero: 'masculino',
    numero: '77049140',
    image: require('../assets/images/clientes/animeman.png'),
  },
  {
    id: 3,
    name: 'Alejandra',
    apellidos: 'Avila',
    ci: '8448556',
    direccion: 'c/las palmas',
    genero: 'femenino',
    numero: '77049140',
    image: require('../assets/images/clientes/animewo.png'),
  },
  {
    id: 4,
    name: 'Mario',
    apellidos: 'Avila',
    ci: '8448556',
    direccion: 'c/las palmas',
    genero: 'masculino',
    numero: '77049140',
    image: require('../assets/images/clientes/animeman.png'),
  },
  {
    id: 5,
    name: 'Jaime',
    apellidos: 'Avila',
    ci: '8448556',
    direccion: 'c/las palmas',
    genero: 'masculino',
    numero: '77049140',
    image: require('../assets/images/clientes/animeman.png'),
  },
  {
    id: 6,
    name: 'Boris',
    apellidos: 'Avila',
    ci: '8448556',
    direccion: 'c/las palmas',
    genero: 'masculino',
    numero: '77049140',
    image: require('../assets/images/clientes/animeman.png'),
  },
  {
    id: 7,
    name: 'Liz',
    apellidos: 'Avila',
    ci: '8448556',
    direccion: 'c/las palmas',
    genero: 'femenino',
    numero: '77049140',
    image: require('../assets/images/clientes/animewo.png'),
  },
  {
    id: 8,
    name: 'Melisa',
    apellidos: 'Avila',
    ci: '8448556',
    direccion: 'c/las palmas',
    genero: 'femenino',
    numero: '77049140',
    image: require('../assets/images/clientes/animewo.png'),
  },
  {
    id: 9,
    name: 'Leni',
    apellidos: 'Avila',
    ci: '8448556',
    direccion: 'c/las palmas',
    genero: 'femenino',
    numero: '77049140',
    image: require('../assets/images/clientes/animewo.png'),
  },
  {
    id: 10,
    name: 'Silvana',
    apellidos: 'Avila',
    ci: '8448556',
    direccion: 'c/las palmas',
    genero: 'femenino',
    numero: '77049140',
    image: require('../assets/images/clientes/animewo.png'),
  },
  {
    id: 11,
    name: 'Laura',
    apellidos: 'Avila',
    ci: '8448556',
    direccion: 'c/las palmas',
    genero: 'femenino',
    numero: '77049140',
    image: require('../assets/images/clientes/animewo.png'),
  },
];

export { clientes };
